### ISSUE TITLE
Error: Socket is already bound

### ISSUE THREAD

**Issue by jczimm** [TooTallNate/node-nat-pmp#8]
I'm using `nat-pmp` for my server.

``` javascript
var natpmp = require('nat-pmp');
...


var client = natpmp.connect("192.168.1.1");

client.portMapping({ private: 8070, public: 8070, ttl: 0 }, function (err, info) {
  if (err) throw err;
      console.log(info);

      // server code
      ...

      client.close();
});
```

On Windows I get this error:

```
$ node main.js
dgram.js:159
    throw new Error('Socket is already bound');
          ^
Error: Socket is already bound
    at Socket.bind (dgram.js:159:11)
    at Client.connect (C:\Users\jczimm\uSocketConsole\node_modules\nat-pmp\index.js:93:15)
    at C:\Users\jczimm\uSocketConsole\node_modules\nat-pmp\index.js:57:12
    at process._tickCallback (node.js:343:11)
    at Function.Module.runMain (module.js:492:11)
    at startup (node.js:124:16)
    at node.js:807:3
```

Does `nat-pmp` simply not work on Windows?  Thanks!

**Comment by Tillman32** [comment]
I'm having this issue too, I can't seem to get it to work. I tried @pose's solution, with no luck.  

dgram.js:161 - Socket Is already bound

**Comment by Vykook** [comment]
Same problem on OS X.

**Comment by SkeletonSlayerz** [comment]
I found the solution. You need to change the following
`exports.CLIENT_PORT = 5352 `
in node-nat-pmp/Index.js to another port that's open.

There's various ports that work. I set it to 0 currently as on OS X it binds to any random kernel selected port. I am not sure about how port 0 works on Linux or Windows.

**Comment by Tillman32** [comment]
@SkeletonSlayerz 
Awesome, thank you! I was able to get it working using 0 as well.

**Comment by SkeletonSlayerz** [comment]
@Tillman32 Yep. Only problem with this is that it doesn't conform to the NAT-PMP standard, but it should be fine if you're only opening the port for a short amount of time. 

I found Bonjour's mDNS to be of the offending nature in this case,  taking up the 5352 Port on Mac. It doesn't set SO_REUSEADDR by default and therefore it turns into the only service that can bind to the port.

**Comment by mikeal** [comment]
Any fix for this?
